repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.1
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]
      exclude: ^venv/

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
    - id: black
      exclude: ^venv/
